### ISSUE TITLE
Worm sampling

### ISSUE THREAD

**Issue by dombrno** [ALPSCore/CT-HYB#15]
Good evening,
I see in the code that some worm sampling capability seems to be implemented. I would be interested in testing it out, for a 2-particle GF calculation, in the non-degenerate 2-band Hubbard model. I have been able to compute some 2p GF with the "standard" sampling, cutting hybridization lines, but the regime which I am targeting now has a very low perturbation order, and thus would require worm. Unfortunately, I could not find any information about the way this feature can be tested/used. What would you recommend?
Thanks a lot.

**Comment by shinaoka** [comment]
Good morning,
Do you want to know how to verify your results?

**Comment by dombrno** [comment]
Not really - I would like to know how to use/activate worm sampling. I cannot find the set of parameters which control worm sampling. If I am able to find this, then I will be able to compare the results with one or two other solvers which I was able to use for that purpose, for which I already have some results.

**Comment by shinaoka** [comment]
Here is a set of input parameters.
You may use measurement.G2.on = 1 and set number of bosonic frequencies and number of Legendre polynomials for fermionic frequencies.
https://github.com/ALPSCore/CT-HYB/wiki/Input-parameters#G2

BTW, I am planning to upgrade the measurement of G2 this year.
I want to see how our new compact representation works with the improved worm estimator for measuring the connected parts.
https://arxiv.org/abs/1803.01916

**Comment by dombrno** [comment]
Oh, you mean that worm is used by default if I set measurement.G2.on = 1 ? I had assumed, for some reason, that the "standard" sampling was the default.

I have seen this recent preprint, it will indeed be very interesting to see how it performs. I must say that until now, I have not been totally successful with Legendre polynomials for the calculation of the dynamic lattice susceptibilities in the 2-band Hubbard model unfortunately.

**Comment by shinaoka** [comment]
Yes, the worm sampling is the default.

The overcompact basis + improved estimator may be the best way.
My guess is that if we use a special type of mesh, its measurement cost will be O(1) like NFFT + improved estimator (but will require much less memory).

**Comment by dombrno** [comment]
OK great thank you, I will give a try then!

**Comment by dombrno** [comment]
Thank you for the help, I will close this issue now!
