### ISSUE TITLE
Omitted #error in no-MPI-detected ifdef

### ISSUE THREAD

**Issue by galexv** [ALPSCore/CT-HYB#3]
This is a minor fix that should make compilation error a bit prettier:
In [src/main.hpp, line 35](https://github.com/ALPSCore/CT-HYB/blob/master/src/main.hpp#L35) the `#error` directive is omitted. It should read:
```c++
#error "non-MPI environment is not supported!"
```

**Comment by shinaoka** [comment]
Thank you. I've fixed it.
