### ISSUE TITLE
If compiler does not support MPI, finding MPI does not work

### ISSUE THREAD

**Issue by galexv** [ALPSCore/CT-HYB#5]
Here is the relevant part of the CMake error log:

>-- Compiler does not support MPI. Trying to find MPI
-- Found MPI_CXX: /usr/lib/libmpi_cxx.so;/usr/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libhwloc.so  
-- MPI : Found compiler /usr/bin/mpicxx
-- MPI : Using /usr/bin/c++
CMake Error at cmake/EnableMPI.cmake:40 (target_include_directories):
  Cannot specify include directories for target "ALPSCoreCTHYB" which is not
  built by this project.
Call Stack (most recent call first):
  CMakeLists.txt:46 (include)
>
>CMake Error at cmake/EnableMPI.cmake:41 (target_link_libraries):
  Cannot specify link libraries for target "ALPSCoreCTHYB" which is not built
  by this project.
Call Stack (most recent call first):
  CMakeLists.txt:46 (include)
>
>-- Configuring incomplete, errors occurred!

**Comment by shinaoka** [comment]
Thank you. I've fixed this bug.

**Comment by shinaoka** [comment]
Thank you. I've fixed this bug.

**Comment by shinaoka** [comment]
Thank you. I've fixed this bug.

**Comment by shinaoka** [comment]
Thank you. I've fixed this bug.
